"""add job boards table

Revision ID: 896da6925331
Revises: 
Create Date: 2025-11-25 14:31:17.283776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896da6925331'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('job_description', sa.String(), nullable=False),
    sa.Column('job_board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_board_id'], ['job_boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_description'),
    sa.UniqueConstraint('job_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posts')
    op.drop_table('job_boards')
    # ### end Alembic commands ###
