"""add job boards table

Revision ID: a50ed3370c95
Revises: bb49822ef137
Create Date: 2025-11-21 15:03:36.588990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50ed3370c95'
down_revision: Union[str, Sequence[str], None] = 'bb49822ef137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('job_description', sa.String(), nullable=False),
    sa.Column('job_board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_board_id'], ['job_boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_description'),
    sa.UniqueConstraint('job_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posts')
    # ### end Alembic commands ###
